### ISSUE TITLE
Does not work with 9.2.2

### ISSUE THREAD

**Issue by rmtew** [lab313ru/ghidra_amiga_ldr#13]
I have Ghidra 9.2.2, and the current 9.2 release of the plugin.

1. I attempted to install the extension and it refused and told me the extension version was wrong.
2. I edited the version file from 9.2 to 9.2.2.
3. I attempted to install the extension and it installed, I restarted Ghidra as requested.
4. I attempted to import an executable file and it only offered Binary file.
5. I click on the (i) icon beside the file type list in the import dialog and see the following.

![image](https://user-images.githubusercontent.com/1057638/110016422-e0c60f00-7d89-11eb-98a2-fcb89c24192f.png)

**Comment by nicodex** [comment]
This should do the trick:
- manually unpack the ZIP to ./Ghidra/Extensions/
- edit the version in /Ghidra/Extensions/ghidra_amiga_ldr/extension.properties
- *and* remove the /Extensions/Ghidra/*_ghidra_amiga_ldr.zip

Personally I skipped the 9.2.1 due to several issues/bugs, ignored the 9.2.2, and wait for the next release :)

**Comment by rmtew** [comment]
No difference.

**Comment by rmtew** [comment]
Okay, I tried another executable and it works but:

- The extension disappears from the "Install Extensions" list although it appears to work.
- My original executable appears incompatible, which I should probably debug.

**Comment by rmtew** [comment]
Okay, the original executable was corrupt, my fault. It appears to work fine. Thanks.
