### ISSUE TITLE
Fill program relocation table (feature request)

### ISSUE THREAD

**Issue by nicodex** [lab313ru/ghidra_amiga_ldr#15]
For my current project it would be nice to have address entries in the program relocation table.

I know that the initial relocation fixup handler has been removed in v1.4 (in the meantime Ghidra requires a different ExtensionPoint class name suffix) and I'm aware of the problems with changing the image base or moving any segments.

Currently I'm trying to build a function ID database from the amiga.lib and Ghidra's hash code skips the bytes referenced by the relocation table. Well, there are still some other issues to solve (FID generator limits, missing cdecl in the processor language spec, ...), but I want to be sure that the relocated bytes do not change the hash.

I also tried to add a pattern file to the loader in data/patterns ([amiga-pattern-test.zip](https://github.com/lab313ru/ghidra_amiga_ldr/files/6125823/amiga-pattern-test.zip)). The function is detected and renamed, but it would result in one huge file and it doesn't help with the function prototypes.

Is anyone working on this or another bigger task? Else I would try to create a PR, but it will probably touch a lot of code...

Best regards, Nico

**Comment by lab313ru** [comment]
Hi,

Actually Ghidra's FID is very limited. In my ghidra_psx_ldr I decided to implement my own json-based signature format, instead of dealing with these limits. It still requires a custom tool to generate signatures, but that signature applier works very well!

So, if you want, you can use my implementation's format as the code base, but it requires to write your own signature disassembler-generator, like I did it for PSX's psyq.

For refs look here: https://github.com/lab313ru/psx_psyq_signatures
