### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by emoon** [lab313ru/ghidra_amiga_ldr#2]
Hi,

I wonder what the current status of this project is? The readme doesn't state if it's usable or not as I'm interested in using this.

**Comment by lab313ru** [comment]
Project is alive. You may try it, but for now supported version is 9.0.2. 
I'll update it soon for 9.0.4

Daniel Collin <notifications@github.com> 11 июня 2019 г. 12:50:26 написал:

**Comment by emoon** [comment]
Awesome! I will give it a go. Thanks :)

**Comment by lab313ru** [comment]
Check the latest release.

**Comment by nicodex** [comment]
> Check the latest release.

Release v1.3 (ghidra_9.0.4_PUBLIC_20190630_ghidra_amiga_ldr.zip) doesn't work with Ghidra v9.0.4 (ghidra_9.0.4_PUBLIC_20190516.zip).

Seems it has been build with JDK v12.0.1 instead of v11.0.2, see https://github.com/lab313ru/ghidra_amiga_ldr/blob/1b9220ee8c9a4dbc76e8b43b29c8cfd3f4766f5f/.classpath#L7

Attached you will find a module build with JDK v11.0.2: 
[ghidra_9.0.4_PUBLIC_20190726_ghidra_amiga_ldr.zip](https://github.com/lab313ru/ghidra_amiga_ldr/files/3435581/ghidra_9.0.4_PUBLIC_20190726_ghidra_amiga_ldr.zip)
